POSTGRE_USER = "postgres"
POSTGRE_PASSWORD = "docker"
POSTGRE_PORT = 5432
POSTGRE_IP = "localhost"
POSTGRE_DB = "postgres"
POSTGRE_CONNECTION = f'postgresql://{POSTGRE_USER}:{POSTGRE_PASSWORD}@{POSTGRE_IP}:{POSTGRE_PORT}/{POSTGRE_DB}'
print(POSTGRE_CONNECTION)
